name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    name: Deploy It
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz -v --stats --progress . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${secrets.APP_HOST_DIRECTORY}

